export { createSDK, FileType } from './client';
export { EditorModeType, EditorStandardRole } from './shared';

export type {
  CreateOptions,
  OfficeSDK,
  DocumentFacade,
  SpreadsheetFacade,
  PdfFacade,
  PresentationFacade,
  LTDocFacade,
  DatabaseTableFacade,
  OfficeSDKMap,
  createContentFacade,
} from './client';
export type {
  EditorContent,
  EditorContentRecord,
  DocumentEditor,
  DocumentRange,
  DocumentRangeValue,
  DocumentSelection,
  DocumentZoom,
  DocumentTOCs,
  DocumentTocItem,
  DocumentTocContentItem,
  DocumentOutline,
  SpreadsheetEditor,
  SpreadsheetWorkbook,
  SpreadsheetWorksheet,
  SpreadsheetCell,
  SpreadsheetSelection,
  SpreadsheetRange,
  SpreadsheetRangeType,
  SpreadsheetRangeValue,
  PdfPages,
  PdfPage,
  PdfSelection,
  PdfRangeValue,
  PdfOutline,
  EditorOutline,
  PdfRange,
  PresentationSelection,
  PresentationZoom,
  PresentationSlides,
  PresentationTextRange,
  PresentationTextRangeValue,
  PresentationShape,
  PresentationSlide,
  EditorOutlineItem,
  EditorContentMethods,
} from './shared';
