export { createSDK, FileType } from './client';
export { EditorModeType, EditorStandardRole } from './shared';

export type {
  CreateOptions,
  OfficeSDK,
  DocumentFacade,
  DocumentSettings,
  SpreadsheetFacade,
  PdfFacade,
  PresentationFacade,
  LTDocFacade,
  DatabaseTableFacade,
  OfficeSDKMap,
  createContentFacade,
  SDKSettings,
} from './client';
export type {
  DocumentEditor,
  DocumentMenuFeatureButtonName,
  DocumentMenuOptions,
  DocumentOutline,
  DocumentRange,
  DocumentRangeBounding,
  DocumentRangeValue,
  DocumentSelection,
  DocumentTOCs,
  DocumentTocContentItem,
  DocumentTocItem,
  DocumentZoom,
  EditorContent,
  EditorContentMethods,
  EditorContentRecord,
  EditorMenuCustomButton,
  EditorMenuEntryConfig,
  EditorMenuFeatureButton,
  EditorMenuEntryButton,
  DocumentMenuEntryConfig,
  DocumentMenuFeatureButtonConfig,
  DocumentOutlineItem,
  DatabaseTableEditor,
  DatabaseTableSDKOptions,
  DatabaseTableMethods,
  EditorMenuFeatureButtonConfig,
  EditorMenuOptions,
  EditorOutline,
  EditorOutlineItem,
  PdfOutline,
  PdfPage,
  PdfPages,
  PdfRange,
  PdfRangeBounding,
  PdfRangeValue,
  PdfSelection,
  PresentationSelection,
  PresentationShape,
  PresentationSlide,
  PresentationSlides,
  PresentationTextRange,
  PresentationTextRangeValue,
  PresentationZoom,
  SpreadsheetCell,
  SpreadsheetEditor,
  SpreadsheetRange,
  SpreadsheetRangeType,
  SpreadsheetRangeValue,
  SpreadsheetSelection,
  SpreadsheetWorkbook,
  SpreadsheetWorksheet,
} from './shared';
