name: Trigger CI via Dispatch

on:
  repository_dispatch:
    types: ['editor_type_updated']

jobs:
  update-editor-dts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log received message
        run: |
          echo "${{ github.event.client_payload.message }}" > payload.log

      - name: Overwrite editor.d.ts
        run: |
          echo "${{ github.event.client_payload.message }}" > packages/officesdk-web/src/shared/editor.ts

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages/officesdk-web/src/shared/editor.ts
          git commit -m "chore: sync editor.ts from GitLab"
          git push