name: Trigger CI via Dispatch

on:
  repository_dispatch:
    types: ['editor_type_updated']

jobs:
  update-editor-dts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log received message
        run: |
          echo "${{ github.event.client_payload.message }}" > payload.log

      - name: update editor-sdk-core
        run: |
          yarn add @officesdk/editor-sdk-core

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./package.json ./yarn.lock
          git commit -m "chore: update editor-sdk-core"
          git push